version: '3'
services:
  db:
    build: ./docker/postgres
  app:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        rm -f tmp/pids/server.pid
        bundle install
        bundle exec rails server -b '0.0.0.0'
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    user: hostuser
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - BUNDLE_PATH=vendor/bundle
